---
apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gitlab
  name: gitlab
  labels: 
    app: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:latest
          ports:
            - containerPort: 80
              name: gitlab
          volumeMounts:
            - name: data-home
              mountPath: /srv/gitlab/data
      volumes:
        - name: data-home
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  namespace: gitlab
  name: gitlab
  labels:
    app: gitlab
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  selector:
    app: gitlab
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: gitlab
  name: gitlab-routing
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: gitlab
          servicePort: 9200
---

