apiVersion: v1
data:
  auth: YWRtaW46JGFwcjEkQ0dsd1VsWVAkVUluWnlPZVhWVmR4RjNqc25oQ3NxMQo=
kind: Secret
metadata:
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:auth: {}
      f:type: {}
    manager: kubectl
    operation: Update
    time: "2020-08-06T11:43:34Z"
  name: mycredentials
  namespace: default
type: Opaque
